apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-neo-controller
  namespace: ingress-nginx-neo
  labels:
    app.kubernetes.io/name: ingress-nginx-neo
    app.kubernetes.io/component: controller
data:
  proxy-connect-timeout: "10"
  proxy-read-timeout: "120"
  proxy-send-timeout: "120"
