apiVersion: v1
data:
  add-headers: "ingress-nginx-neo/custom-headers"
kind: ConfigMap
metadata:
  name: ingress-nginx-neo-controller
  namespace: ingress-nginx-neo
  labels:
    app.kubernetes.io/name: ingress-nginx-neo
    app.kubernetes.io/component: controller
