// SPDX-License-Identifier: Apache-2.0

// Command flagsdoc writes docs/user-guide/cli-arguments.md from the flag set
// of the controller (make docs-generate).
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/spf13/pflag"

	"k8s.io/ingress-nginx/pkg/flags"
)

const header = `# Command line arguments

The following command line arguments are accepted by the Ingress controller executable.

They are set in the container spec of the controller Deployment or DaemonSet; the Helm chart
passes them with ` + "`controller.extraArgs`" + `.

<!-- Generated by make docs-generate from pkg/flags; do not edit. -->

| Argument | Description |
|----------|-------------|
`

func main() {
	output := flag.String("output", "", "where to write the documentation")
	flag.Parse()
	if *output == "" {
		fmt.Fprintln(os.Stderr, "-output is required")
		os.Exit(2)
	}

	set, _ := flags.NewFlagSet()

	var doc bytes.Buffer
	doc.WriteString(header)
	set.VisitAll(func(f *pflag.Flag) {
		fmt.Fprintf(&doc, "| `--%s` | %s |\n", f.Name, description(f))
	})

	if err := os.WriteFile(*output, doc.Bytes(), 0o644); err != nil { //nolint:gosec // documentation is world readable
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// description returns the usage text of a flag on one line, followed by its
// default value when it is not the zero value of its type.
func description(f *pflag.Flag) string {
	text := strings.Join(strings.Fields(f.Usage), " ")
	text = strings.ReplaceAll(text, "|", `\|`)
	switch f.DefValue {
	case "", "0", "false", "[]", "0s", "<nil>":
		return text
	}
	def := f.DefValue
	if f.Value.Type() == "string" {
		def = fmt.Sprintf("%q", def)
	}
	return fmt.Sprintf("%s (default %s)", text, strings.ReplaceAll(def, "|", `\|`))
}
